### ISSUE TITLE
Samsung SSD temperature is not reported

### ISSUE THREAD

**Issue by redskinhu** [Drewster727/hddtemp-docker#2]
Hello

I have a small problem.

I replaced my HDD to SSD. The hddtemp.db didn't contains the relevant settings to this SSD.
I found the solution: i added this line to the `/etc/hddtemp.db`
`"Samsung SSD 850 PRO 256G B"<--><------><------><------>190  C  "Samsung SSD 850 PRO 256GB"`

After this if I use the normal command line hddtemp I get the proper values.
```
hddtemp /dev/sda1
/dev/sda1: Samsung SSD 850 PRO 256G B              ▒@: 34°C
```
If I request the docker hddtemp output I got this (the HDD reported well before):
```
nc localhost 7634
|/dev/sda1|Samsung SSD 850 PRO 256G B              ▒@|UNK|*|
```
How can I add the settings to the docker hddtemp?

Thanks
T

**Comment by Drewster727** [comment]
scratch that -- I just added that and a couple other samsung models. Try to get the latest docker image.
