### ISSUE TITLE
unnecessary steps

### ISSUE THREAD

**Issue by Zeka13** [Drewster727/hddtemp-docker#3]
1. dont need to install build-essential ?
2. dont need mount /var/run/docker.sock ? 
3. dont need write access to /dev
4. no reason for use net host

**Comment by Drewster727** [comment]
you're absolutely correct. I think some of this was hold-over from a couple years ago, specifically running on unraid. 

Still need to make sure build-essential isn't needed, but you could be right.

readme updated. Thanks!
